add links to be saved in database
NazarValko/djinni-parser pull request #14
Opened 2024-04-19 19:13 UTC by NazarValko

2024-04-25 07:00 UTC, vitokro requested changes

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +        List<String> parsedLinks = Arrays.asList("http://link1.com", "http://link2.com");
List.of()

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +        List<String> expectedLinks = Arrays.asList("http://link1.com", "http://link2.com");
List.of()

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +@TestPropertySource(locations = "classpath:application-test.properties")
@TestPropertySource(locations = "classpath:application-test.properties") is not necessary here. Because when you use @ActiveProfiles("test") that means that   will be used instead of application.properties

2024-04-25 07:00 UTC, vitokro commented on src/test/resources/application-test.properties
> +spring.datasource.url=jdbc:h2:file:./src/main/test/resources/parser_database_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
No need to create to store db file into the hard drive. Create in-memory DB for testing

2024-04-25 07:00 UTC, vitokro commented on src/test/resources/application-test.properties
> +spring.sql.init.mode=always
This file should be next one to application.properties

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +        jdbcTemplate = new JdbcTemplate(dataSource);
You may autowire jdbcTemplate and not create it everytime

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +    private DataSource dataSource;
If you autowire jdbcTemplate you will not longer be in need of this datasource here

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +        jdbcTemplate.execute("delete from parsers_links;");
create in-memory db and delete this method

2024-04-25 07:00 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +        String resourceId = "testResource";
create const for this var

2024-04-25 07:00 UTC, vitokro commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS link_providers (
Add descriptions for tables and all fields. Everything should be uppercased

2024-04-25 07:00 UTC, vitokro commented on src/main/java/org/nazar/service/dao/VacancyDBDao.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
create bean in configuration and just autowire jdbcTemplate

2024-04-25 09:57 UTC, NazarValko commented on src/main/java/org/nazar/service/dao/VacancyDBDao.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
fix

2024-04-25 09:58 UTC, NazarValko commented
fix

2024-04-27 11:30 UTC, vitokro requested changes

2024-04-27 11:30 UTC, vitokro commented on src/test/java/org/nazar/service/dao/VacancyDBDaoTest.java
> +    private final String RESOURCE_ID = "testResource";
add static

2024-04-28 06:46 UTC, vitokro approved these changes

2024-04-28 08:22 UTC, merged